apiVersion: v1
kind: Service
metadata:
  name: netty
  labels:
    app: netty
spec:
  type: NodePort 
  ports:
  - port: 8081
    targetPort: 8081
    nodePort: 30001
  selector:
    app: netty
---
apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: netty
spec:
  selector:
    matchLabels:
      app: netty
  replicas: 6
  template:
    metadata:
      labels:
        app: netty
    spec:
      containers:
      - name: netty
        image: duongvt16/netty-app:test-{{BUILD_ID}}
        resources:
          requests:
            cpu: 500m
            memory: 300Mi
        ports:
        - containerPort: 8081
